version: "3.1"

services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      POSTGRES_DB: catalog_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: rigwild/catalog-api
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      PGHOST: db
      PGUSER : postgres
      PGPASSWORD : postgres
